# THIS FILE IS AUTOGENERATED. DO NOT EDIT.

_callbacks = {
    "UnivariateDistribution": """
class UnivariateDistribution {
  constructor() {
    
    this.hardMin = -Infinity;
    this.hardMax = Infinity;

    
    this.paramNames = [];

    
    this.fixedParams = [];
  }

  generateActiveFixedInds() {
    
    this.activeParamsInds = [];
    this.fixedParamsInds = []
    for (let i = 0; i < this.paramNames.length; i++) {
      if (this.fixedParams.includes(this.paramNames[i])) {
        this.fixedParamsInds.push(i);
      } else {
        this.activeParamsInds.push(i);
      }
    }
  }

  xMin(params) {
    
  }

  xMax(params) {
    
  }

  cdfSingleValue(x, params, xMin = 0) {
    
  }

  ppfSingleValue(p, params, xMin = 0, xMax = Infinity, p1Value = Infinity) {
    
  }

  quantileSet(x, p, extraParams = []) {
    
  }

  defaultXRange(params) {
    
  }


  cdf(x, params, xMin = 0) {
    params = this.scalarToArrayParams(params);

    return this.scalarOrArrayCompute(
      (x, params) => this.cdfSingleValue(x, params, xMin),
      x,
      params
    );
  }

  ppfSingleValueWithCheck(p, params, xMin = 0, xMax = Infinity, p1Value = Infinity) {
    if (p < 0 || p > 1) return NaN;
    return this.ppfSingleValue(p, params, xMin, xMax, p1Value);
  }

  ppf(p, params, xMin = 0, xMax = Infinity, p1Value = Infinity) {
    params = this.scalarToArrayParams(params);

    return this.scalarOrArrayCompute(
      (p, params) => this.ppfSingleValueWithCheck(p, params, xMin, xMax, p1Value),
      p,
      params
    );
  }

  resetXRange(params, p) {
    if (p === undefined) {
      return this.defaultXRange(params);
    } else if (this.checkResetp(p)) {
      return this.ppf(p, params);
    }
  }

  scalarOrArrayCompute(func, x, params) {
    if (x instanceof Array) {
      let xLen = x.length;

      let res = [];
      for (let i = 0; i < xLen; i++) {
        res.push(func(x[i], params));
      }

      return res;
    } else {
      return func(x, params);
    }
  }

  scalarToArrayParams(params) {
    return params instanceof Array ? params : [params]
  }
}
""",
    "DiscreteUnivariateDistribution": """
class DiscreteUnivariateDistribution extends UnivariateDistribution {
  constructor() {
    super();
  }

  pmfSingleValue(x, params) {
    
  }

  pmf(x, params) {
    params = this.scalarToArrayParams(params);

    return this.scalarOrArrayCompute(
      (x, params) => this.pmfSingleValue(x, params),
      x,
      params);
  }

  cdfSingleValue(x, params, xMin = 0) {
    params = this.scalarToArrayParams(params);

    
    let cumsum = 0.0;
    let summand = 0.0;
    for (let n = xMin; n <= x; n++) {
        summand = this.pmfSingleValue(n, params);
        if (!isNaN(summand)) cumsum += summand;
    }

    return cumsum;
  }

  cdfForPlotting(xStart, xEnd, params, xMin = 0) {

    params = this.scalarToArrayParams(params);

    
    let cumsum = 0.0;
    let prob;
    for (let x = xMin; x < xStart; x++) {
      prob = this.pmfSingleValue(x, params);
      if (!isNaN(prob)) cumsum += prob;
    }

    
    let yCDF = [];
    for (let x = xStart; x < xEnd; x++) {
      prob = this.pmfSingleValue(x, params);
      if (!isNaN(prob)) cumsum += prob;
      yCDF.push(cumsum, cumsum);
    }

    return yCDF;
  }

  ppfSingleValue(p, params, xMin = 0, xMax = Infinity, p1Value = Infinity) {
    
    if (p == 0) return xMin;

    
    if (p == 1) return p1Value;

    params = this.scalarToArrayParams(params);

    
    let n = xMin;
    let cumsum = this.pmfSingleValue(n, params);

    let iters = 0;
    let summand = 0.0;
    while (cumsum < p && !isclose(cumsum, p) && !isNaN(summand) && n < xMax) {
      n += 1;
      summand = this.pmfSingleValue(n, params);

      if (!isNaN(summand)) cumsum += summand;

      iters += 1;
    }

    return n;
  }

}
""",
    "ContinuousUnivariateDistribution": """
class ContinuousUnivariateDistribution extends UnivariateDistribution {
  constructor() {
    super();
  }

  pdfSingleValue(x, params) {
    
  }

  pdf(x, params) {
    params = this.scalarToArrayParams(params);

    return this.scalarOrArrayCompute(
      (x, params) => this.pdfSingleValue(x, params),
      x,
      params
    );
  }

}
""",
    "TemplateDiscreteUnivariateDistribution": """
class TemplateDiscreteUnivariateDistribution extends DiscreteUnivariateDistribution {
  constructor() {
    super();

    
    this.name = '';

    
    this.varName = '';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = [];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()

    
  }

  xMin(params) {
    
  }

  xMax(params) {
    
  }

  pmfSingleValue(x, params) {
    
  }

  defaultXRange(params) {
    
  }

  quantileSet(x, p, extraParams = []) {
    
  }

}
""",
    "TemplateContinuousUnivariateDistribution": """
class TemplateContinuousUnivariateDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = '';

    
    this.varName = '';

    
    this.hardMin = -Infinity;
    this.hardMax = Infinity;

    
    this.paramNames = [];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()

    
  }

  xMin(params) {
    
  }

  xMax(params) {
    
  }

  pdfSingleValue(x, params) {
    
  }

  cdfSingleValue(x, params) {
    
  }

  ppfSingleValue(p, params) {
    
  }

  defaultXRange(params) {
    
  }

  quantileSet(x, p, extraParams = []) {
    
  }

  
}
""",
    "BernoulliDistribution": """
class BernoulliDistribution extends DiscreteUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Bernoulli';

    
    this.varName = 'y';

    
    this.hardMin = 0;
    this.hardMax = 1;

    
    this.paramNames = ['θ'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0;
  }

  xMax(params) {
    return 1;
  }

  pmfSingleValue(x, params) {
    let theta = params[0];

    if (x == 0) return 1 - theta;
    else if (x == 1) return theta;
    else return NaN;
  }

  ppfSingleValue(p, params) {
    if (p <= params[0]) return 0;
    else return 1;
  }

  defaultXRange(params) {
    return [-0.2, 1.2];
  }

}
""",
    "BetaBinomialDistribution": """
class BetaBinomialDistribution extends DiscreteUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'BetaBinomial';

    
    this.varName = 'n';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = ['N', 'α', 'β'];

    
    this.fixedParams = ['N'];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0;
  }

  xMax(params) {
    return params[0];
  }

  pmfSingleValue(n, params) {
    let [N, alpha, beta] = params.slice(0, 3);

    if (n > N || n < 0) return NaN;

    return Math.exp(lnchoice(N, n) + lnbeta(n + alpha, N - n + beta) - lnbeta(alpha, beta));
  }

  ppfSingleValue(p, params) {
    let [N, alpha, beta] = params.slice(0, 3);

    return super.ppfSingleValue(p, params, 0, N, N);
  }

  defaultXRange(params) {
    let [N, alpha, beta] = params.slice(0, 3);

    return [-1, N + 1];
  }

}
""",
    "BinomialDistribution": """
class BinomialDistribution extends DiscreteUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Binomial';

    
    this.varName = 'n';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = ['N', 'θ'];

    
    this.fixedParams = ['N'];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0;
  }

  xMax(params) {
    return params[0];
  }

  pmfSingleValue(n, params) {
    let [N, theta] = params.slice(0, 2);

    if (n > N || n < 0) return NaN;

    if (theta == 0) {
      if (n == 0) return 1.0;
      return 0.0;
    }

    if (theta == 1) {
      if (n == N) return 1.0;
      return 0.0;
    }

    return Math.exp(lnchoice(N, n) +
      n * Math.log(theta) +
      (N - n) * Math.log(1 - theta));
  }

  ppfSingleValue(p, params) {
    let [N, theta] = params.slice(0, 2);
    
    return super.ppfSingleValue(p, params, 0, N, N);
  }

  defaultXRange(params) {
    let [N, theta] = params.slice(0, 2);

    if (N < 50) {
      return [-1, N + 1];
    } else {
      return this.ppf([0.001, 0.999], params);
    }
  }
}
""",
    "CategoricalDistribution": """
class CategoricalDistribution extends DiscreteUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Categorical';

    
    this.varName = 'y';

    
    this.hardMin = 1;
    this.hardMax = 4;

    
    this.paramNames = ['θ1', 'θ2', 'θ3'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 1;
  }

  xMax(params) {
    return 4;
  }

  pmfSingleValue(cat, params) {
    let [theta1, theta2, theta3] = params.slice(0, 3);
    let theta4 = 1 - theta1 - theta2 - theta3

    
    if (theta4 < 0) return NaN;

    
    if (![1, 2, 3, 4].includes(cat)) return NaN;

    let probs = [theta1, theta2, theta3, theta4]

    return probs[cat-1];
  }

  defaultXRange(params) {
    return [-0.2, 4.2];
  }

}
""",
    "DiscreteUniformDistribution": """
class DiscreteUniformDistribution extends DiscreteUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'DiscreteUniform';

    
    this.varName = '';

    
    this.hardMin = -Infinity;
    this.hardMax = Infinity;

    
    this.paramNames = ['low', 'high'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return params[0];
  }

  xMax(params) {
    return params[1];
  }

  pmfSingleValue(n, params) {
    let [low, high] = params.slice(0, 2);

    if (low > high || n < low || n > high) return NaN;

    return 1 / (high - low + 1);
  }

  ppfSingleValue(p, params) {
    let [low, high] = params.slice(0, 2);
    
    return super.ppfSingleValue(p, params, low, high, high);
  }

  defaultXRange(params) {
    let [low, high] = params.slice(0, 2);

    return [low - 1, high + 1];
  }

}
""",
    "GeometricDistribution": """
class GeometricDistribution extends DiscreteUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Geometric';

    
    this.varName = 'y';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = ['θ'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0;
  }

  xMax(params) {
    return Infinity;
  }

  pmfSingleValue(x, params) {
    let theta = params[0];

    if (theta == 1) {
      if (x == 0) return 1.0;
      return 0.0;
    }

    if (theta == 0) return 0.0;

    if (x < 0) return NaN;

    return Math.exp(x * Math.log(1.0 - theta) + Math.log(theta));
  }

  ppfSingleValue(p, params) {
    let theta = params[0];

    if (p == 0) return 0;
    if (p == 1) return Infinity;

    let res = Math.ceil(Math.log(1 - p) / Math.log(1 - theta) - 1);

    if (res === -0) return 0;
    return res;
  }

  defaultXRange(params) {
    let theta = params[0];

    return [-1, this.ppfSingleValue(0.999, params)];
  }

}
""",
    "HypergeometricDistribution": """
class HypergeometricDistribution extends DiscreteUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Hypergeometric';

    
    this.varName = 'n';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = ['N', 'a', 'b'];

    
    this.fixedParams = ['N'];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    let [N, a, b] = params.slice(0, 2);
    return Math.max(0, N - b);
  }

  xMax(params) {
    return Math.min(N, a);
  }

  pmfSingleValue(n, params) {
    let [N, a, b] = params.slice(0, 2);

    if (n < Math.max(0, N - b) || n > Math.min(N, a)) return NaN;

    return Math.exp(lnchoice(a, n) + lnchoice(b, N - n) - lnchoice(a + b, N));
  }

  ppfSingleValue(p, params) {
    let [N, alpha, beta] = params.slice(0, 3);

    return super.ppfSingleValue(p, params, this.xMin(params), this.xMax(params), this.xMax(params));
  }

  defaultXRange(params) {
    let [N, alpha, beta] = params.slice(0, 3);

    return [Math.max(0, N - b) - 1, Math.min(N, a) + 1];
  }
}
""",
    "NegativeBinomialDistribution": """
class NegativeBinomialDistribution extends DiscreteUnivariateDistribution {
  constructor(parametrization) {
    super();

    
    this.name = 'NegativeBinomial';

    
    this.varName = 'y';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    if (parametrization === undefined) {
      this.parametrization = 'alpha-beta'
    } else {
      this.parametrization = parametrization;
    }

    
    if (this.parametrization === 'alpha-beta') {
      this.paramNames = ['α', 'β'];
    } else if (this.parametrization === 'mu-phi') {
      this.paramNames = ['µ', 'φ'];
    } else if (this.parametrization === 'r-b') {
      this.paramNames = ['r', 'b'];
    } else { 
      this.paramNames = ['unnamedParam1', 'unnamedParam2'];
    }

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0;
  }

  xMax(params) {
    return Infinity;
  }

  pmfSingleValue(y, params) {
    if (y < 0) return NaN;

    if (this.parametrization === 'alpha-beta') {
      let [alpha, beta] = params.slice(0, 2);

      if (alpha <= 0 || beta <= 0) return NaN;

      return Math.exp(lngamma(y + alpha)
                      - lngamma(alpha)
                      - lnfactorial(y)
                      + alpha * Math.log(beta / (1 + beta))
                      - y * Math.log(1 + beta));
    } else if (this.parametrization === 'mu-phi') {
      let [mu, phi] = params.slice(0, 2);
      
      if (mu <= 0 || phi <= 0) return NaN;

      let logMuPhi = Math.log(mu + phi);

      return Math.exp(lngamma(y + phi)
                      - lngamma(phi)
                      - lnfactorial(y)
                      + phi * (Math.log(phi) - logMuPhi)
                      + y * (Math.log(mu) - logMuPhi));
    } else if (this.parametrization === 'r-b') {
      let [r, b] = params.slice(0, 2);
      
      if (r <= 0 || b <= 0) return NaN;

      return Math.exp(lngamma(y + r)
                      - lngamma(r)
                      - lnfactorial(y)
                      + r * Math.log(1 / (1 + b))
                      - y * Math.log(1 + 1 / b));
    }
  }

  defaultXRange(params) {
    return super.ppf([0.001, 0.999], params)
  }

}
""",
    "NegativeBinomialMuPhiDistribution": """
class NegativeBinomialMuPhiDistribution extends NegativeBinomialDistribution {
  constructor() {
    super('mu-phi');
  }
}
""",
    "NegativeBinomialRBDistribution": """
class NegativeBinomialRBDistribution extends NegativeBinomialDistribution {
  constructor() {
    super('r-b');
  }
}
""",
    "PoissonDistribution": """
class PoissonDistribution extends DiscreteUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Poisson';

    
    this.varName = 'n';  

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = ['λ'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0;
  }

  xMax(params) {
    return Infinity;
  }

  pmfSingleValue(n, params) {
    let lam = params[0];

    if (lam < 0) {
      return NaN;
    } else if (lam == 0) {
      if (n == 0) return 1.0;
      return 0.0;
    }

    return Math.exp(n * Math.log(lam) - lnfactorial(n) - lam);
  }

  defaultXRange(params) {
    return super.ppf([0.001, 0.999], params)
  }

}
""",
    "BetaDistribution": """
class BetaDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Beta';

    
    this.varName = 'θ';

    
    this.hardMin = 0;
    this.hardMax = 1;

    
    this.paramNames = ['α', 'β'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0.0;
  }

  xMax(params) {
    return 1.0;
  }

  pdfSingleValue(x, params) {
    let [alpha, beta] = params.slice(0, 2);

    if (x < 0 || x > 1) return NaN;

    if (iszero(x)) {
        if (alpha == 1) {
            return Math.exp(-lnbeta(alpha, beta));
        } else if (alpha > 1) {
            return 0.0;
        } else {
            return Infinity;
        }
    }
    else if (isone(x)) {
        if (beta == 1) {
            return Math.exp(-lnbeta(alpha, beta));
        }
        else if (beta > 1) {
            return 0.0;
        }
        else {
            return Infinity;
        }
    }

    let lnProb = (alpha - 1.0) * Math.log(x) + (beta - 1.0) * Math.log(1.0 - x) - lnbeta(alpha, beta);

    return Math.exp(lnProb);
  }

  cdfSingleValue(x, params) {
    let [alpha, beta] = params.slice(0, 2);

    if (x <= 0) return 0.0;
    if (x >= 1) return 1.0;

    return regularizedIncompleteBeta(x, alpha, beta);
  }

  ppfSingleValue(p, params) {
    if (p == 0) return 0.0;
    if (p == 1) return 1.0;

    
    let rootFun = (x, params, p) => p - this.cdfSingleValue(x, params);
    
    return brentSolve(rootFun, 0.0, 1.0, [params, p]);
  }

  quantileSet(x, p) {
    let [x1, x2] = x.slice(0, 2);
    let [p1, p2] = p.slice(0, 2);

    
    const quantileRootFun = (params, x1, p1, x2, p2) => {
      let alpha = Math.exp(params[0]);
      let beta = Math.exp(params[1]);

      let r1 = this.cdfSingleValue(x1, [alpha, beta]) - p1;
      let r2 = this.cdfSingleValue(x2, [alpha, beta]) - p2;

      return [r1, r2];
    };

    let args = [x1, p1, x2, p2];
    let guess = [1.0, 1.0];
    let [logParams, optimSuccess] = findRootTrustRegion(quantileRootFun, guess, args=args);

    return [[Math.exp(logParams[0]), Math.exp(logParams[1])], optimSuccess];
  }

  defaultXRange(params) {
    return [0.0, 1.0];
  }

}
""",
    "CauchyDistribution": """
class CauchyDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Cauchy';

    
    this.varName = 'y';

    
    this.hardMin = -Infinity;
    this.hardMax = Infinity;

    
    this.paramNames = ['μ', 'σ'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return -Infinity;
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    if (x == Infinity || x == -Infinity) return 0.0;

    let [mu, sigma] = params.slice(0, 2);

    return 1.0 / Math.PI / sigma / (1 + Math.pow((x - mu) / sigma, 2))
  }

  cdfSingleValue(x, params) {
    let [mu, sigma] = params.slice(0, 2);

    return 0.5 + Math.atan((x - mu) / sigma) / Math.PI;
  }

  ppfSingleValue(p, params) {
    let [mu, sigma] = params.slice(0, 2);

    return mu + sigma * Math.tan(Math.PI * (p - 0.5));
  }

  defaultXRange(params) {
    
    return this.ppf([0.025, 0.975], params);
  }

  quantileSet(x, p) {
    let [x1, x2] = x.slice(0, 2);
    let [p1, p2] = p.slice(0, 2);

    let cotp1 = 1.0 / Math.tan(Math.PI * p1);
    let cotp2 = 1.0 / Math.tan(Math.PI * p2);

    let mu = (x2 * cotp1 - x1 * cotp2) / (cotp1 - cotp2);
    let sigma = (x1 - x2) * Math.sin(Math.PI * p1) * Math.sin(Math.PI * p1) 
                / Math.sin(Math.PI * (p1 - p2));

    return [[mu, sigma], true];
  }
}
""",
    "ExponentialDistribution": """
class ExponentialDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Exponential';

    
    this.varName = 'y';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = ['β'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0.0;
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    let beta = params[0];

    if (x < 0) return NaN;
    if (x == Infinity) return 0.0;

    return beta * Math.exp(-beta * x);
  }

  cdfSingleValue(x, params) {
    let beta = params[0];

    if (x < 0) return 0.0;
    if (x == Infinity) return 0.0;

    return 1 - Math.exp(-beta * x);
  }

  ppfSingleValue(p, params) {
    let beta = params[0];

    if (p == 0) return 0.0;
    if (p == 1) return Infinity;

    return -Math.log(1.0 - p) / beta;
  }

  quantileSet(x, p) {
    let x1 = x[0];
    let p1 = p[0];

    return [[-Math.log(1.0 - p1) / x1], true];
  }

  defaultXRange(params) {
    return [0.0, this.ppfSingleValue(0.999, params)];
  }

}
""",
    "GammaDistribution": """
class GammaDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Gamma';

    
    this.varName = 'y';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = ['α', 'β'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0.0;   
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    if (x < 0) return NaN;
    if (x == Infinity) return 0.0;

    let [alpha, beta] = params.slice(0, 2);

    if (x == 0) {
      if (alpha == 1) {
        return beta;
      } else if (alpha > 1) {
        return 0.0;
      } else {  
        return Infinity;
      }
    }

    let lnProb;
    lnProb = alpha * Math.log(beta * x) - Math.log(x) - beta * x - lngamma(alpha);

    return Math.exp(lnProb);
  }

  cdfSingleValue(x, params) {
    if (x <= 0) return 0.0;
    if (x == Infinity) return 1.0;

    let [alpha, beta] = params.slice(0, 2);

    return gammaincL(beta * x, alpha, true);
  }

  ppfSingleValue(p, params) {
    if (p === 0) return 0.0;
    if (p === 1) return Infinity;

    
    let rescaledParams = [params[0], 1.0];

    let rootFun = (xi, params, p) => {
        let x = xi == 1.0 ? Infinity : xi / (1.0 - xi);

        return p - this.cdfSingleValue(x, params);
    }

    let xiOpt = brentSolve(rootFun, 0.0, 1.0, [rescaledParams, p]);

    
    if (xiOpt === 1) {
      return Infinity;
    }

    
    let xFirstPass = xiOpt / (1.0 - xiOpt);

    let closeRootFun = (x, params, p) => {
      return p - this.cdfSingleValue(x, params);
    }

    let xOpt = secantSolve(xFirstPass, closeRootFun, [rescaledParams, p]);

    let retval;
    if (xOpt != null && closeRootFun(xOpt, rescaledParams, p) < closeRootFun(xFirstPass, rescaledParams, p)) {
      retval = xOpt;
    } else {
      retval = xFirstPass;
    }

    
    return retval / params[1];
 }

  defaultXRange(params) {
    let [x1, x2] = this.ppf([0.001, 0.999], params);

    
    if (x1 < (x2 - x1) / 10.0) x1 = 0.0;

    return [x1, x2];
  }

  quantileSet(x, p) {
    let [x1, x2] = x.slice(0, 2);
    let [p1, p2] = p.slice(0, 2);

    
    let x1Rescaled = x1 / x2;
    let x2Rescaled = 1.0;

    
    const quantileRootFun = (params, x1, p1, x2, p2) => {
      let alpha = Math.exp(params[0]);
      let beta = Math.exp(params[1]);

      let r1 = this.cdfSingleValue(x1, [alpha, beta]) - p1;
      let r2 = this.cdfSingleValue(x2, [alpha, beta]) - p2;

      return [r1, r2];
    };

    let args = [x1Rescaled, p1, x2Rescaled, p2];

    let guess = [0.75, 0.75];

    let [logParams, optimSuccess] = findRootTrustRegion(quantileRootFun, guess, args=args);

    
    let paramsFirstPass = [Math.exp(logParams[0]), Math.exp(logParams[1])];

    
    if (!optimSuccess) {
      return [[paramsFirstPass[0], paramsFirstPass[1]], optimSuccess];
    }

    
    const closeQuantileRootFun = (params, x1, p1, x2, p2) => {
      let r1 = this.cdfSingleValue(x1, params) - p1;
      let r2 = this.cdfSingleValue(x2, params) - p2;

      return [r1, r2];
    };

    let paramsOpt;
    [paramsOpt, optimSuccess] = findRootTrustRegion(closeQuantileRootFun, paramsFirstPass, args=args);

    let retval;
    if (optimSuccess && norm(closeQuantileRootFun(paramsOpt, x1, p1, x2, p2)) < norm(closeQuantileRootFun(paramsFirstPass, x1, p1, x2, p2))) {
      retval = paramsOpt;
    } else {
      retval = paramsFirstPass;
    }

    
    return [[retval[0], retval[1] / x2], optimSuccess];
  }

}
""",
    "HalfCauchyDistribution": """
class HalfCauchyDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'HalfCauchy';

    
    this.varName = 'y';

    
    this.hardMin = -Infinity;
    this.hardMax = Infinity;

    
    this.paramNames = ['µ', 'σ'];

    
    this.fixedParams = ['µ'];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return params[0];
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    let [mu, sigma] = params.slice(0, 2);

    if (x < mu) return NaN;
    if (x === Infinity) return 0.0;

    return 2.0 / Math.PI / sigma / (1 + Math.pow((x - mu) / sigma, 2));
  }

  cdfSingleValue(x, params) {
    let [mu, sigma] = params.slice(0, 2);

    if (x <= mu) return 0.0;
    if (x === Infinity) return 1.0;

    return 2.0 * Math.atan((x - mu) / sigma) / Math.PI;
  }

  ppfSingleValue(p, params) {
    let [mu, sigma] = params.slice(0, 2);

    return mu + sigma * Math.tan(Math.PI * p / 2.0);
  }

  defaultXRange(params) {
    
    return [params[0], this.ppf(0.9, params)];
  }

  quantileSet(x, p, extraParams) {
    let x1 = x[0];
    let p1 = p[0];
    let mu = extraParams[0];

    return [[(x1 - mu) / Math.tan(Math.PI * p1 / 2)], true];
  }
}
""",
    "HalfNormalDistribution": """
class HalfNormalDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'HalfNormal';

    
    this.varName = 'y';

    
    this.hardMin = -Infinity;
    this.hardMax = Infinity;

    
    this.paramNames = ['µ', 'σ'];

    
    this.fixedParams = ['µ'];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return params[0];
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    let [mu, sigma] = params.slice(0, 2);

    if (x < mu) return NaN;
    if (x === Infinity) return 0.0;

    let expTerm = (Math.pow(x - mu, 2) / 2.0 / Math.pow(sigma, 2));
    return Math.exp(-expTerm) / sigma * Math.sqrt(2.0 / Math.PI);
  }

  cdfSingleValue(x, params) {
    let [mu, sigma] = params.slice(0, 2);

    if (x <= mu) return 0.0;
    if (x === Infinity) return 1.0;

    return erf((x - mu) / sigma / Math.sqrt(2));
  }

  ppfSingleValue(p, params) {
    let [mu, sigma] = params.slice(0, 2);
    let sqrt2 = 1.4142135623730951;

    return mu + sqrt2 * sigma * erfinv(p);
  }

  defaultXRange(params) {
    return [params[0], this.ppf(0.999, params)];
  }

  quantileSet(x, p, extraParams) {
    let x1 = x[0];
    let p1 = p[0];
    let mu = extraParams[0];

    let sqrt2 = 1.4142135623730951;

    return [[(x1 - mu) / sqrt2 / erfinv(p1)], true];
  }
}
""",
    "HalfStudentTDistribution": """
class HalfStudentTDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'HalfStudentT';

    
    this.varName = 'y';

    
    this.hardMin = -Infinity;
    this.hardMax = Infinity;

    
    this.paramNames = ['ν', 'µ', 'σ'];

    
    this.fixedParams = ['ν', 'µ'];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return params[1];
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    let [nu, mu, sigma] = params.slice(0, 3);

    if (x < mu) return NaN;
    if (x === Infinity) return 0.0;

    let lnprob;

    lnprob = Math.log(2.0) + lngamma((nu + 1) / 2) - lngamma(nu / 2) - Math.log(Math.PI * nu) / 2 
             - Math.log(sigma) - (nu + 1) / 2 * log1p(Math.pow(x - mu, 2) / nu / Math.pow(sigma, 2));

    return Math.exp(lnprob);
  }

  cdfSingleValue(x, params) {
    let [nu, mu, sigma] = params.slice(0, 3);

    if (x <= mu) return 0.0;
    if (x === Infinity) return 1.0;

    let y = (x - mu) / sigma;

    return 1 - regularizedIncompleteBeta(nu / (Math.pow(y, 2) + nu), 0.5 * nu, 0.5);
  }

  ppfSingleValue(p, params) {
    if (p === 0) return params[1];
    if (p === 1) return Infinity;

    let studentT = new StudentTDistribution();
    return studentT.ppf((1 + p) / 2, params);
  }

  defaultXRange(params) {
    return [params[0], this.ppf(0.999, params)];
  }

  quantileSet(x, p, extraParams) {
    let [nu, mu] = extraParams;

    
    if (nu === 1) { 
      let halfCauchy = new HalfCauchyDistribution();
      return halfCauchy.quantileSet(x, p, [mu]);
    }
    if (nu === Infinity) { 
      let halfNormal = new HalfNormalDistribution();
      return halfNormal.quantileSet(x, p, [mu]);
    }

    let x1 = x[0];
    let p1 = p[0];

    
    const quantileRootFun = (params, nu, mu, x1, p1) => {
      let sigma = Math.exp(params[0]);

      return [this.cdfSingleValue(x1, [nu, mu, sigma]) - p1];
    };

    let args = [nu, mu, x1, p1];

    
    let guess;
    let guessSuccess;
    if (nu < 3) {
      let halfCauchy = new HalfCauchyDistribution();
      [guess, guessSuccess] = halfCauchy.quantileSet(x, p, [mu]);
    } else {
      let halfNormal = new HalfNormalDistribution();
      [guess, guessSuccess] = halfNormal.quantileSet(x, p, [mu]);      
    }

    
    guess = [Math.log(guess[0])];

    let [paramsFirstPass, optimSuccess] = findRootTrustRegion(quantileRootFun, guess, args=args);

    
    paramsFirstPass[0] = Math.exp(paramsFirstPass[0]);

    
    if (!optimSuccess) {
      return [[paramsFirstPass[0]], optimSuccess];
    }

    
    const closeQuantileRootFun = (params, nu, mu, x1, p1) => {
      let sigma = params[0];

      return [this.cdfSingleValue(x1, [nu, mu, sigma]) - p1];
    };

    let paramsOpt;
    [paramsOpt, optimSuccess] = findRootTrustRegion(closeQuantileRootFun, paramsFirstPass, args=args);

    let retval;
    if (optimSuccess && norm(closeQuantileRootFun(paramsOpt, nu, x1, p1)) < norm(closeQuantileRootFun(paramsFirstPass, nu, x1, p1))) {
      retval = [paramsOpt, optimSuccess];
    } else {
      retval = [paramsOpt, optimSuccess];
    }

    return retval;
  }
}
""",
    "InverseGammaDistribution": """
class InverseGammaDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'InverseGamma';

    
    this.varName = 'y';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = ['α', 'β'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0.0;   
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    if (x < 0) return NaN;
    if (x === 0 || x === Infinity) return 0.0;

    let [alpha, beta] = params.slice(0, 2);

    let lnProb;
    lnProb = alpha * Math.log(beta) - (alpha + 1) * Math.log(x) - beta / x - lngamma(alpha);

    return Math.exp(lnProb);
  }

  cdfSingleValue(x, params) {
    if (x <= 0) return 0.0;
    if (x == Infinity) return 1.0;

    let [alpha, beta] = params.slice(0, 2);

    return gammaincU(beta / x, alpha, true);
  }

  ppfSingleValue(p, params) {
    if (p === 0) return 0.0;
    if (p === 1) return Infinity;

    let gamma = new GammaDistribution();
    return 1.0 / gamma.ppf(1.0 - p, params);
  }

  defaultXRange(params) {
    
    let [x1, x2] = this.ppf([0.001, 0.99], params);

    
    if (x1 < (x2 - x1) / 10.0) x1 = 0.0;

    return [x1, x2];
  }

  quantileSet(x, p) {
    let [x1, x2] = x.slice(0, 2);

    let gamma = new GammaDistribution();
    return gamma.quantileSet([1.0 / x2, 1.0 / x1], p);
  }

}
""",
    "LogNormalDistribution": """
class LogNormalDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'LogNormal';

    
    this.varName = 'y';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = ['μ', 'σ'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
}

  xMin(params) {
    return 0.0;
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    if (x < 0.0) return NaN;
    if (x === 0) return 0.0;
    if (x === Infinity) return 0.0;

    let [mu, sigma] = params.slice(0, 2);
    let expTerm = (Math.pow(Math.log(x) - mu, 2) / 2.0 / Math.pow(sigma, 2))
    return Math.exp(-expTerm) / x / sigma / Math.sqrt(2 * Math.PI);
  }

  cdfSingleValue(x, params) {
    if (x <= 0) return 0.0;
    if (x === Infinity) return 1.0;

    let [mu, sigma] = params.slice(0, 2);
    return (1 + erf((Math.log(x) - mu) / sigma / Math.sqrt(2))) / 2;
  }

  ppfSingleValue(p, params) {
    if (p === 0) return 0.0;
    if (p === 1) return Infinity;

    let [mu, sigma] = params.slice(0, 2);
    let sqrt2 = 1.4142135623730951;

    return Math.exp(mu + sqrt2 * sigma * erfinv(2 * p - 1));
  }

  defaultXRange(params) {
    
    let [x1, x2] = this.ppf([0.001, 0.99], params);

    
    if (x1 < (x2 - x1) / 10.0) x1 = 0.0;

    return [x1, x2];
  }

  quantileSet(x, p) {
    let [x1, x2] = x.slice(0, 2);
    let [p1, p2] = p.slice(0, 2);
    let [logx1, logx2] = [Math.log(x1), Math.log(x2)];

    let sqrt2 = 1.4142135623730951;

    let sigmaCoeff1 = sqrt2 * erfinv(2 * p1 - 1);
    let sigmaCoeff2 = sqrt2 * erfinv(2 * p2 - 1);

    let sigma = (logx2 - logx1) / (sigmaCoeff2 - sigmaCoeff1);
    let mu = logx2 - sigmaCoeff2 * sigma;

    return [[mu, sigma], true];
  }
}
""",
    "NormalDistribution": """
class NormalDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Normal';

    
    this.varName = 'y';

    
    this.hardMin = -Infinity;
    this.hardMax = Infinity;

    
    this.paramNames = ['μ', 'σ'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
}

  xMin(params) {
    return -Infinity;
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    if (x === -Infinity || x === Infinity) return 0.0;

    let [mu, sigma] = params.slice(0, 2);

    let expTerm = (Math.pow(x - mu, 2) / 2.0 / Math.pow(sigma, 2));
    return Math.exp(-expTerm) / sigma / Math.sqrt(2 * Math.PI);
  }

  cdfSingleValue(x, params) {
    if (x === -Infinity) return 0.0;
    if (x === Infinity) return 1.0;

    let [mu, sigma] = params.slice(0, 2);

    return (1 + erf((x - mu) / sigma / Math.sqrt(2))) / 2;
  }

  ppfSingleValue(p, params) {
    if (p === 0) return -Infinity;
    if (p === 1) return Infinity;

    let [mu, sigma] = params.slice(0, 2);
    let sqrt2 = 1.4142135623730951;

    return mu + sqrt2 * sigma * erfinv(2 * p - 1);
  }

  defaultXRange(params) {
    return this.ppf([0.001, 0.999], params);
  }

  quantileSet(x, p) {
    let [x1, x2] = x.slice(0, 2);
    let [p1, p2] = p.slice(0, 2);

    let sqrt2 = 1.4142135623730951;

    let sigmaCoeff1 = sqrt2 * erfinv(2 * p1 - 1);
    let sigmaCoeff2 = sqrt2 * erfinv(2 * p2 - 1);

    let sigma = (x2 - x1) / (sigmaCoeff2 - sigmaCoeff1);
    let mu = x2 - sigmaCoeff2 * sigma;

    return [[mu, sigma], true];
  }
}
""",
    "ParetoDistribution": """
class ParetoDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Pareto';

    
    this.varName = 'y';

    
    this.hardMin = 0;
    this.hardMax = Infinity;

    
    this.paramNames = ['yₘᵢₙ', 'α'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return params[0];    
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    let [ymin, alpha] = params.slice(0, 2);

    if (x < ymin) return NaN;
    if (x === Infinity) return 0.0;

    let logp = Math.log(alpha) + alpha * Math.log(ymin) - (alpha + 1) * Math.log(x); 
    return Math.exp(logp);
  }

  cdfSingleValue(x, params) {
    let [ymin, alpha] = params.slice(0, 2);

    if (x <= ymin) return 0.0;
    if (x === Infinity) return 1.0;

    return 1 - Math.pow(ymin / x, alpha);
  }

  ppfSingleValue(p, params) {
    let [ymin, alpha] = params.slice(0, 2);

    if (p === 0) return ymin;
    if (p === 1) return Infinity;

    return ymin * Math.pow(1.0 / (1.0 - p), 1.0 / alpha);
  }

  defaultXRange(params) {
    
    let [ymin, alpha] = params.slice(0, 2);

    let p = 0.01;

    let x1 = ymin;
    let logx2 = Math.log(ymin) - Math.log(p) / (1 + alpha);
    let x2 = Math.exp(logx2);

    return [x1, x2];
  }

  quantileSet(x, p) {
    let [x1, x2] = x.slice(0, 2);
    let [p1, p2] = p.slice(0, 2);

    let alpha = (Math.log(1.0 - p1) - Math.log(1.0 - p2)) / (Math.log(x2) - Math.log(x1));
    let ymin = Math.exp(Math.log(1 - p2) / alpha + Math.log(x2));

    return [[ymin, alpha], true];
  }
}
""",
    "StudentTDistribution": """
class StudentTDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'StudentT';

    
    this.varName = 'y';

    
    this.hardMin = -Infinity;
    this.hardMax = Infinity;

    
    this.paramNames = ['ν', 'μ', 'σ'];

    
    this.fixedParams = ['ν'];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return -Infinity;
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    if (x === -Infinity || x === Infinity) return 0.0;

    let [nu, mu, sigma] = params.slice(0, 3);

    let lnprob;

    lnprob = lngamma((nu + 1) / 2) - lngamma(nu / 2) - Math.log(Math.PI * nu) / 2 - Math.log(sigma)
             - (nu + 1) / 2 * log1p(Math.pow(x - mu, 2) / nu / Math.pow(sigma, 2));

    return Math.exp(lnprob);
  }

  cdfSingleValue(x, params) {
    if (x === -Infinity) return 0.0;
    if (x === Infinity) return 1.0;

    let [nu, mu, sigma] = params.slice(0, 3);

    let y = (x - mu) / sigma;

    if (y >= 0) {
        return 1 - regularizedIncompleteBeta(nu / (Math.pow(y, 2) + nu), 0.5 * nu, 0.5) / 2;
    }
    else {
        return regularizedIncompleteBeta(nu / (Math.pow(y, 2) + nu), 0.5 * nu, 0.5) / 2;        
    }
  }

  ppfSingleValue(p, params) {
    let [nu, mu, sigma] = params.slice(0, 3);

    
    let guess;
    if (nu < 3) { 
      guess = Math.tan(Math.PI * (p - 0.5));
    } else {
      guess = Math.sqrt(2) * erfinv(2 * p - 1)
    }

    
    if (nu === 1 || nu === Infinity) return mu + sigma * guess;

    
    let rootFun = (x, nu, p) => [p - this.cdfSingleValue(x, [nu, 0, 1])];
    let [xOpt, success] = findRootTrustRegion(rootFun, [guess], [nu, p]);

    return mu + sigma * xOpt[0];
  }

  defaultXRange(params) {
    
    let [nu, mu, sigma] = params.slice(0, 3);

    let p1;
    let p2;

    if (nu < 2) {
        p1 = 0.05;
        p2 = 0.95;
    }
    if (nu < 4) {
        p1 = 0.01;
        p2 = 0.99;
    }
    else if (nu < 10) {
        p1 = 0.005;
        p2 = 0.995;
    }
    else {
        p1 = 0.001;
        p2 = 0.999;
    }

    return this.ppf([p1, p2], params);
  }

  quantileSet(x, p, extraParams) {

    let nu = extraParams[0];

    
    if (nu === 1) { 
      let cauchy = new CauchyDistribution();
      return cauchy.quantileSet(x, p);
    }
    if (nu === Infinity) { 
      let normal = new NormalDistribution();
      return normal.quantileSet(x, p);
    }

    let [x1, x2] = x.slice(0, 2);
    let [p1, p2] = p.slice(0, 2);

    
    const quantileRootFun = (params, nu, x1, p1, x2, p2) => {
      let mu = params[0];
      let sigma = Math.exp(params[1]);

      let r1 = this.cdfSingleValue(x1, [nu, mu, sigma]) - p1;
      let r2 = this.cdfSingleValue(x2, [nu, mu, sigma]) - p2;

      return [r1, r2];
    };

    let args = [nu, x1, p1, x2, p2];

    
    let guess;
    let guessSuccess;
    if (nu < 3) {
      let cauchy = new CauchyDistribution();
      [guess, guessSuccess] = cauchy.quantileSet(x, p);
    } else {
      let normal = new NormalDistribution();
      [guess, guessSuccess] = normal.quantileSet(x, p);      
    }

    
    guess = [guess[0], Math.log(guess[1])];

    let [paramsFirstPass, optimSuccess] = findRootTrustRegion(quantileRootFun, guess, args=args);

    
    paramsFirstPass[1] = Math.exp(paramsFirstPass[1]);

    
    if (!optimSuccess) {
      return [[paramsFirstPass[0], paramsFirstPass[1]], optimSuccess];
    }

    
    const closeQuantileRootFun = (params, nu, x1, p1, x2, p2) => {
      let [mu, sigma] = params.slice(0, 2);

      let r1 = this.cdfSingleValue(x1, [nu, mu, sigma]) - p1;
      let r2 = this.cdfSingleValue(x2, [nu, mu, sigma]) - p2;

      return [r1, r2];
    };

    let paramsOpt;
    [paramsOpt, optimSuccess] = findRootTrustRegion(closeQuantileRootFun, paramsFirstPass, args=args);

    let retval;
    if (optimSuccess && norm(closeQuantileRootFun(paramsOpt, nu, x1, p1, x2, p2)) < norm(closeQuantileRootFun(paramsFirstPass, nu, x1, p1, x2, p2))) {
      retval = [paramsOpt, optimSuccess];
    } else {
      retval = [paramsOpt, optimSuccess];
    }

    return retval;
  }

}
""",
    "UniformDistribution": """
class UniformDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Uniform';

    
    this.varName = 'y';

    
    this.hardMin = -Infinity;
    this.hardMax = Infinity;

    
    this.paramNames = ['α', 'β'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return params[0];    
  }

  xMax(params) {
    return params[1];    
  }

  pdfSingleValue(x, params) {
    let [alpha, beta] = params.slice(0, 2);
    
    if (beta <= alpha || x < alpha || x > beta) return NaN;

    return 1.0 / (beta - alpha);
  }

  cdfSingleValue(x, params) {
    let [alpha, beta] = params.slice(0, 2);

    if (beta <= alpha) return NaN;

    if (x <= alpha) return 0.0;
    if (x >= beta) return 1.0;

    return (x - alpha) / (beta - alpha);
  }

  ppfSingleValue(p, params) {
    let [alpha, beta] = params.slice(0, 2);

    if (beta <= alpha) return NaN;

    return alpha + p * (beta - alpha);
  }

  defaultXRange(params) {
    let [alpha, beta] = params.slice(0, 2);

    if (beta <= alpha) return [0, 1];

    let d = beta - alpha;
    
    return[alpha - d * 0.1, beta + d * 0.1];
  }

  quantileSet(x, p, extraParams = []) {
    let [x1, x2] = x.slice(0, 2);
    let [p1, p2] = p.slice(0, 2);

    let alpha = (p2 * x1 - p1 * x2) / (p2 - p1);
    let beta = alpha + (x2 - x1) / (p2 - p1);

    return [[alpha, beta], true];
  }
}
""",
    "WeibullDistribution": """
class WeibullDistribution extends ContinuousUnivariateDistribution {
  constructor() {
    super();

    
    this.name = 'Weibull';

    
    this.varName = 'y';

    
    this.hardMin = 0.0;
    this.hardMax = Infinity;

    
    this.paramNames = ['α', 'σ'];

    
    this.fixedParams = [];

    
    super.generateActiveFixedInds()
  }

  xMin(params) {
    return 0.0;
  }

  xMax(params) {
    return Infinity;
  }

  pdfSingleValue(x, params) {
    if (x < 0) return NaN;
    if (x === 0) return 0.0;
    if (x === Infinity) return 0.0;

    let [alpha, sigma] = params.slice(0, 2);

    let logp = -Math.pow(x / sigma, alpha) + (alpha - 1) * Math.log(x) 
                + Math.log(alpha) - alpha * Math.log(sigma);

    return Math.exp(logp);
  }

  cdfSingleValue(x, params) {
    if (x <= 0) return 0.0;
    if (x === Infinity) return 1.0;

    let [alpha, sigma] = params.slice(0, 2);

    return 1 - Math.exp(-Math.pow(x / sigma, alpha));
  }

  ppfSingleValue(p, params) {
    if (p === 0) return 0.0;
    if (p === 1) return Infinity;

    let [alpha, sigma] = params.slice(0, 2);

    return sigma * Math.pow(-Math.log(1.0 - p), 1.0 / alpha);
  }

  defaultXRange(params) {
    let [x1, x2] = this.ppf([0.001, 0.999], params);

    
    if (x1 < (x2 - x1) / 10.0) x1 = 0.0;

    return [x1, x2];
  }

  quantileSet(x, p, extraParams = []) {
    let [x1, x2] = x.slice(0, 2);
    let [p1, p2] = p.slice(0, 2);

    let loglog1 = Math.log(-Math.log(1.0 - p1));
    let loglog2 = Math.log(-Math.log(1.0 - p2));
    let logx1 = Math.log(x1);
    let logx2 = Math.log(x2);

    let alpha = (loglog2 - loglog1) / (logx2 - logx1);
    let sigma = Math.exp(logx2 - loglog2 / alpha);

    return [[alpha, sigma], true];
  }

  
}
""",
    "isclose": """
function isclose(x, y, rtol = 1.0e-7, atol = 1.0e-8) {
  return Math.abs(x - y) <= (atol + rtol * Math.abs(y));
}

""",
    "isone": """
function isone(x, rtol = 1.0e-5, atol = 1.0e-8) {
  return isclose(x, 1.0, rtol, atol);
}

""",
    "iszero": """
function iszero(x, eps = 1.0e-8) {
  return Math.abs(x) <= eps;
}

""",
    "logspace": """
function logspace(start, stop, n) {
  let x = new Array(n);
  let step = (stop - start) / (n - 1);
  for (let i = 0; i < n; i++) {
    x[i] = Math.pow(10, start + i * step);
  }

  return x;
}

""",
    "linspace": """
function linspace(start, stop, n) {
  let x = new Array(n);
  let step = (stop - start) / (n - 1);
  for (let i = 0; i < n; i++) {
    x[i] = start + i * step;
  }

  return x;
}

""",
    "arange": """
function arange(start, stop) {
  let x = new Array(stop - start);
  for (let i = 0; i < stop - start; i++) {
    x[i] = start + i;
  }

  return x;
}

""",
    "meshgrid": """
function meshgrid(x, y) {
  let m = y.length;
  let n = x.length;

  let xGrid = new Array(m);
  let yGrid = new Array(m);

  for (let i = 0; i < m; i++) {
    xGrid[i] = new Array(n);
    yGrid[i] = new Array(n);
    for (let j = 0; j < n; j++) {
      xGrid[i][j] = x[j];
      yGrid[i][j] = y[i];
    }
  }

  return [xGrid, yGrid];
}

""",
    "logit": """
function logit(x) {
  if (x == 0) return -Infinity;

  if (x == 1) return Infinity;

  if (x < 0 || x > 1) return NaN;

  return Math.log(x / (1.0 - x));
}

""",
    "log1p": """
function log1p(x) {
  
  
  if (x <= -1.0) {
    throw new RangeError('Argument must be greater than -1.0');
  }

  
  else if (Math.abs(x) > 1e-4) {
    return Math.log(1.0 + x);
  }

  else {
    return (-0.5*x + 1.0)*x;
  }
}

""",
    "erf": """
function erf(x) {
  
  var a = [1.00002368,
           0.37409196,
           0.09678418,
           -0.18628806,
           0.27886807,
           -1.13520398,
           1.48851587,
           -0.82215223,
           0.17087277];

  var t = 1 / (1 + Math.abs(x)/2);
  var expSum = -Math.pow(x, 2) - 1.26551223;

  for (var i = 0; i < a.length; i++) {
      expSum += a[i] * Math.pow(t, i+1);
  }

  var result = 1 - t * Math.exp(expSum);

  if (x < 0) return -result;
  return result;
}

""",
    "erfinv": """
function erfinv(x) {
  
  let p = (x + 1.0) / 2.0;

  
  if (p == 0.0) return -Infinity;
  if (p == 1.0) return Infinity;
  if (p > 1.0 || p < 0.0) return undefined;

  let split1 = 0.425;
  let split2 = 5.0;
  let const1 = 0.180625;
  let const2 = 1.6;

  
  let a0 = 3.3871327179;
  let a1 = 5.0434271938e1;
  let a2 = 1.5929113202e2;
  let a3 = 5.9109374720e1;
  let b1 = 1.7895169469e1;
  let b2 = 7.8757757664e1;
  let b3 = 6.7187563600e1;

  
  let c0 = 1.4234372777;
  let c1 = 2.7568153900;
  let c2 = 1.3067284816;
  let c3 = 1.7023821103e-1;
  let d1 = 7.3700164250e-1;
  let d2 = 1.2021132975e-1;

  
  let e0 = 6.6579051150;
  let e1 = 3.0812263860;
  let e2 = 4.2868294337e-1;
  let e3 = 1.7337203997e-2;
  let f1 = 2.4197894225e-1;
  let f2 = 1.2258202635e-2;

  let r;
  let res;
  let q = p - 0.5;

  if (Math.abs(q) <= split1) {
    r = const1 - q * q;
    res = q * (((a3 * r + a2) * r + a1) * r + a0) /
              (((b3 * r + b2) * r + b1) * r + 1.0);
  } else {
    r = q < 0 ? p : 1.0 - p;

    r = Math.sqrt(-Math.log(r));

    if (r <= split2) {
      r -= const2;
      res = (((c3 * r + c2) * r + c1) * r + c0) /
             ((d2 * r + d1) * r + 1.0);
    } else {
      r -= split2;
      res = (((e3 * r + e2) * r + e1) * r + e0) /
             ((f2 * r + f1) * r + 1.0);
    }
  
    if (q < 0) {
      res = -res;
    }
  }

  
  return 0.7071067811865475 * res;

}

""",
    "lnchoice": """
function lnchoice(n, k) {
    return lnfactorial(n) - lnfactorial(n-k) - lnfactorial(k);
}

""",
    "lnbeta": """
function lnbeta(x, y) {
    if (x < 0 || y < 0) {
        throw RangeError('Arguments must be positive.');
    }
    else if (x === 0 && y === 0) return NaN;
    else if (x === 0 || y === 0) return Infinity;

    return lngamma(x) + lngamma(y) - lngamma(x + y);
}

""",
    "betacf": """
function betacf(x, a, b) {
    
    
    var fpmin = 1e-30,
        m = 1,
        m2, aa, c, d, del, h, qab, qam, qap;
    
    qab = a + b;
    qap = a + 1;
    qam = a - 1;
    c = 1;
    d = 1 - qab * x / qap;
    if (Math.abs(d) < fpmin) d = fpmin;
    d = 1 / d;
    h = d;
    for (; m <= 100; m++) {
        m2 = 2 * m;
        aa = m * (b - m) * x / ((qam + m2) * (a + m2));
        
        d = 1 + aa * d;
        if (Math.abs(d) < fpmin) d = fpmin;
        c = 1 + aa / c;
        if (Math.abs(c) < fpmin) c = fpmin;
        d = 1 / d;
        h *= d * c;
        aa = -(a + m) * (qab + m) * x / ((a + m2) * (qap + m2));
        
        d = 1 + aa * d;
        if (Math.abs(d) < fpmin) d = fpmin;
        c = 1 + aa / c;
        if (Math.abs(c) < fpmin) c = fpmin;
        d = 1 / d;
        del = d * c;
        h *= del;
        if (Math.abs(del - 1.0) < 3e-7) break;
    }
    return h;
}

""",
    "regularizedIncompleteBeta": """
function regularizedIncompleteBeta(x, a, b) {
    
    
    if (x < 0 || x > 1) {
        throw new RangeError('First argument must be between 0 and 1.');
    }

    
    else if (a === 1 && b === 1) return x;
    else if (x === 0) return 0;
    else if (x === 1) return 1;
    else if (a === 0) return 1;
    else if (b === 0) return 0;

    else {
        var bt = Math.exp(lngamma(a + b) - lngamma(a) - lngamma(b) + a * Math.log(x) + b * log1p(-x));

        
        if (x < (a + 1) / (a + b + 2)) return bt * betacf(x, a, b) / a;

        
        else return 1 - bt * betacf(1 - x, b, a) / b;
    }
}

""",
    "incompleteBeta": """
function incompleteBeta(x, a, b) {
    return regularizedIncompleteBeta(x, a, b) * Math.exp(lnbeta(a, b));
}

""",
    "lngamma": """
function lngamma(z) {

    if(z < 0) return Number('0/0');

    if (z < 0.5) return Math.log(Math.PI) - Math.log(Math.sin(Math.PI * z)) - lngamma(1-z);

    var p = [676.5203681218851,
             -1259.1392167224028,
             771.32342877765313,
             -176.61502916214059,
             12.507343278686905,
             -0.13857109526572012,
             9.9843695780195716e-6,
             1.5056327351493116e-7];

    z -= 1.0;
    var Ag = 0.99999999999980993;
    for (var i = 0; i < p.length; i++) {
        Ag += p[i] / (z + i + 1);
    }
    var t = z + p.length - 0.5;

    return 0.5 * Math.log(2*Math.PI) + (z + 0.5)*Math.log(t) - t + Math.log(Ag);
}

""",
    "gammaincU": """
function gammaincU(x, s, regularized) {
    
    var EPSILON = 1e-12;

    if (x <= 1.1 || x <= s) {
        if (regularized !== false) {
            return 1 - gammaincL(x, s, regularized);
        } else {
            return Math.exp(lngamma(s)) - gammaincL(x, s, regularized);
        }
    }

    var f = 1 + x - s,
        C = f,
        D = 0,
        i = 1,
        a, b, chg;
    for (i = 1; i < 10000; i++) {
        a = i * (s - i);
        b = (i<<1) + 1 + x - s;
        D = b + a * D;
        C = b + a / C;
        D = 1 / D;
        chg = C * D;
        f *= chg;
        if (Math.abs(chg - 1) < EPSILON) {
            break;
        }
    }
    if (regularized !== false) {
        return Math.exp(s * Math.log(x) - x - lngamma(s) - Math.log(f));
    } else {
        return Math.exp(s * Math.log(x) - x - Math.log(f));
    }
}

""",
    "gammaincL": """
function gammaincL(x, s, regularized) {
    
    var EPSILON = 1e-12;

    if (x === 0) {
        return 0;
    }
    if (x < 0 || s <= 0) {
        return NaN;
    }

    if(x > 1.1 && x > s) {
        if (regularized !== false) {
            return 1 - gammaincU(x, s, regularized);
        } else {
            return Math.exp(lngamma(s)) - gammaincU(x, s, regularized);
        }
    }

    var ft,
        r = s,
        c = 1,
        pws = 1;

    if (regularized !== false) {
        ft = s * Math.log(x) - x - lngamma(s);
    } else {
        ft = s * Math.log(x) - x;
    }
    ft = Math.exp(ft);
    do {
        r += 1;
        c *= x/r;
        pws += c;
    } while (c / pws > EPSILON);
    return pws*ft/s;
}

""",
    "lnfactorial": """
function lnfactorial(n) {
  if (n > 254) { 
    let x = n + 1;
    return (x - 0.5) * Math.log(x) - x + 0.5 * Math.log(2 * Math.PI) + 1.0 / (12.0 * x);
  }
  else { 
    const lnfact = [0.000000000000000,
                    0.000000000000000,
                    0.693147180559945,
                    1.791759469228055,
                    3.178053830347946,
                    4.787491742782046,
                    6.579251212010101,
                    8.525161361065415,
                    10.604602902745251,
                    12.801827480081469,
                    15.104412573075516,
                    17.502307845873887,
                    19.987214495661885,
                    22.552163853123421,
                    25.191221182738683,
                    27.899271383840894,
                    30.671860106080675,
                    33.505073450136891,
                    36.395445208033053,
                    39.339884187199495,
                    42.335616460753485,
                    45.380138898476908,
                    48.471181351835227,
                    51.606675567764377,
                    54.784729398112319,
                    58.003605222980518,
                    61.261701761002001,
                    64.557538627006323,
                    67.889743137181526,
                    71.257038967168000,
                    74.658236348830158,
                    78.092223553315307,
                    81.557959456115029,
                    85.054467017581516,
                    88.580827542197682,
                    92.136175603687079,
                    95.719694542143202,
                    99.330612454787428,
                    102.968198614513810,
                    106.631760260643450,
                    110.320639714757390,
                    114.034211781461690,
                    117.771881399745060,
                    121.533081515438640,
                    125.317271149356880,
                    129.123933639127240,
                    132.952575035616290,
                    136.802722637326350,
                    140.673923648234250,
                    144.565743946344900,
                    148.477766951773020,
                    152.409592584497350,
                    156.360836303078800,
                    160.331128216630930,
                    164.320112263195170,
                    168.327445448427650,
                    172.352797139162820,
                    176.395848406997370,
                    180.456291417543780,
                    184.533828861449510,
                    188.628173423671600,
                    192.739047287844900,
                    196.866181672889980,
                    201.009316399281570,
                    205.168199482641200,
                    209.342586752536820,
                    213.532241494563270,
                    217.736934113954250,
                    221.956441819130360,
                    226.190548323727570,
                    230.439043565776930,
                    234.701723442818260,
                    238.978389561834350,
                    243.268849002982730,
                    247.572914096186910,
                    251.890402209723190,
                    256.221135550009480,
                    260.564940971863220,
                    264.921649798552780,
                    269.291097651019810,
                    273.673124285693690,
                    278.067573440366120,
                    282.474292687630400,
                    286.893133295426990,
                    291.323950094270290,
                    295.766601350760600,
                    300.220948647014100,
                    304.686856765668720,
                    309.164193580146900,
                    313.652829949878990,
                    318.152639620209300,
                    322.663499126726210,
                    327.185287703775200,
                    331.717887196928470,
                    336.261181979198450,
                    340.815058870798960,
                    345.379407062266860,
                    349.954118040770250,
                    354.539085519440790,
                    359.134205369575340,
                    363.739375555563470,
                    368.354496072404690,
                    372.979468885689020,
                    377.614197873918670,
                    382.258588773060010,
                    386.912549123217560,
                    391.575988217329610,
                    396.248817051791490,
                    400.930948278915760,
                    405.622296161144900,
                    410.322776526937280,
                    415.032306728249580,
                    419.750805599544780,
                    424.478193418257090,
                    429.214391866651570,
                    433.959323995014870,
                    438.712914186121170,
                    443.475088120918940,
                    448.245772745384610,
                    453.024896238496130,
                    457.812387981278110,
                    462.608178526874890,
                    467.412199571608080,
                    472.224383926980520,
                    477.044665492585580,
                    481.872979229887900,
                    486.709261136839360,
                    491.553448223298010,
                    496.405478487217580,
                    501.265290891579240,
                    506.132825342034830,
                    511.008022665236070,
                    515.890824587822520,
                    520.781173716044240,
                    525.679013515995050,
                    530.584288294433580,
                    535.496943180169520,
                    540.416924105997740,
                    545.344177791154950,
                    550.278651724285620,
                    555.220294146894960,
                    560.169054037273100,
                    565.124881094874350,
                    570.087725725134190,
                    575.057539024710200,
                    580.034272767130800,
                    585.017879388839220,
                    590.008311975617860,
                    595.005524249382010,
                    600.009470555327430,
                    605.020105849423770,
                    610.037385686238740,
                    615.061266207084940,
                    620.091704128477430,
                    625.128656730891070,
                    630.172081847810200,
                    635.221937855059760,
                    640.278183660408100,
                    645.340778693435030,
                    650.409682895655240,
                    655.484856710889060,
                    660.566261075873510,
                    665.653857411105950,
                    670.747607611912710,
                    675.847474039736880,
                    680.953419513637530,
                    686.065407301994010,
                    691.183401114410800,
                    696.307365093814040,
                    701.437263808737160,
                    706.573062245787470,
                    711.714725802289990,
                    716.862220279103440,
                    722.015511873601330,
                    727.174567172815840,
                    732.339353146739310,
                    737.509837141777440,
                    742.685986874351220,
                    747.867770424643370,
                    753.055156230484160,
                    758.248113081374300,
                    763.446610112640200,
                    768.650616799717000,
                    773.860102952558460,
                    779.075038710167410,
                    784.295394535245690,
                    789.521141208958970,
                    794.752249825813460,
                    799.988691788643450,
                    805.230438803703120,
                    810.477462875863580,
                    815.729736303910160,
                    820.987231675937890,
                    826.249921864842800,
                    831.517780023906310,
                    836.790779582469900,
                    842.068894241700490,
                    847.352097970438420,
                    852.640365001133090,
                    857.933669825857460,
                    863.231987192405430,
                    868.535292100464630,
                    873.843559797865740,
                    879.156765776907600,
                    884.474885770751830,
                    889.797895749890240,
                    895.125771918679900,
                    900.458490711945270,
                    905.796028791646340,
                    911.138363043611210,
                    916.485470574328820,
                    921.837328707804890,
                    927.193914982476710,
                    932.555207148186240,
                    937.921183163208070,
                    943.291821191335660,
                    948.667099599019820,
                    954.046996952560450,
                    959.431492015349480,
                    964.820563745165940,
                    970.214191291518320,
                    975.612353993036210,
                    981.015031374908400,
                    986.422203146368590,
                    991.833849198223450,
                    997.249949600427840,
                    1002.670484599700300,
                    1008.095434617181700,
                    1013.524780246136200,
                    1018.958502249690200,
                    1024.396581558613400,
                    1029.838999269135500,
                    1035.285736640801600,
                    1040.736775094367400,
                    1046.192096209724900,
                    1051.651681723869200,
                    1057.115513528895000,
                    1062.583573670030100,
                    1068.055844343701400,
                    1073.532307895632800,
                    1079.012946818975000,
                    1084.497743752465600,
                    1089.986681478622400,
                    1095.479742921962700,
                    1100.976911147256000,
                    1106.478169357800900,
                    1111.983500893733000,
                    1117.492889230361000,
                    1123.006317976526100,
                    1128.523770872990800,
                    1134.045231790853000,
                    1139.570684729984800,
                    1145.100113817496100,
                    1150.633503306223700,
                    1156.170837573242400];
    return lnfact[n];
  }
}

""",
    "transpose": """
function transpose(A) {
    return A[0].map((_, colIndex) => A.map(row => row[colIndex]));
}

""",
    "mvMult": """
function mvMult(A, v) {
  return A.map(Arow => dot(Arow, v));
}

""",
    "svMult": """
function svMult(a, v) {
  return v.map(x => a * x);
}

""",
    "smMult": """
function smMult(a, A) {
  return A.map(Arow => svMult(a, Arow));
}

""",
    "svAdd": """
function svAdd(a, v) {
  return v.map(x => a + x);
}

""",
    "mmMult": """
function mmMult(A, B) {
  let mA = A.length;
  let nA = A[0].length;
  let mB = B.length;
  let nB = B[0].length;

  if (nA !== mB) {
      throw new Error('Matrix dimension mismatch.');
  }

  let result = zeros(mA, nB);

  for (let i = 0; i < mA; i++) {
    for (let j = 0; j < nB; j++) {
      for (let k = 0; k < nA; k++) {
        result[i][j] += A[i][k] * B[k][j];
      }
    }
  }

  return result;
}

""",
    "vectorAdd": """
function vectorAdd() {
  let m = arguments.length;
  let n = arguments[0].length;
 
  let result = new Array(n).fill(0.0);
 
  for (let i = 0; i < n; i++) {
    for (let j = 0; j < m; j++) {
        result[i] += arguments[j][i];
    }
  }

  return result;
}

""",
    "elementwiseVectorDivide": """
function elementwiseVectorDivide(v1, v2) {
  return v1.map((value, i) => value / v2[i]);
}

""",
    "elementwiseVectorMult": """
function elementwiseVectorMult(v1, v2) {
  return v1.map((value, i) => value * v2[i]);
}

""",
    "svMultAdd": """
function svMultAdd(scalars, vectors) {
  let m = scalars.length;
  let n = vectors[0].length;

  if (vectors.length != m) {
      console.warn("svMultAdd: Different number of scalars and vectors.");
      return null;
  }

  let result = new Array(n).fill(0.0);
  for (let i = 0; i < n; i++) {
    for (let j = 0; j < m; j++) {
      result[i] += scalars[j] * vectors[j][i];
    }
  }

  return result;
}

""",
    "absVector": """
function absVector(v) {
  return v.map(x => Math.abs(x));
}

""",
    "dot": """
function dot(v1, v2) {
  const n = v1.length;
  var result = 0.0;
  for (let i = 0; i < n; i++) result += v1[i] * v2[i];

  return result;
}

""",
    "norm": """
function norm(v) {
  return Math.sqrt(dot(v, v));
}

""",
    "quadForm": """
function quadForm(A, x) {
   return dot(x, mvMult(A, x)); 
}

""",
    "shallowCopyMatrix": """
function shallowCopyMatrix(A) {
  var Ac = [];
  var n = A.length;
  for (i = 0; i < n; i++) {
      Ac.push([...A[i]]);
  }

  return Ac;
}

""",
    "deepCopy": """
function deepCopy(x) {
  return JSON.parse(JSON.stringify(x));
}

""",
    "zeros": """
function zeros(...dims) {
  let A = [];

  
  for (let i = dims.length - 1; i >= 0; i--) {
    let size = dims[i];
    if (i === dims.length - 1) {
      
      A = new Array(size).fill(0.0);
    } else {
      
      A = new Array(size).fill().map(() => deepCopy(A));
    }
  }

  return A;
}

""",
    "lowerTriSolve": """
function lowerTriSolve(L, b) {
    const floatEps = 1.0e-14;
    const n = L.length;

    
    let x = Array.from(b);

    
    for (let j = 0; j < n - 1; j++) {
        if (Math.abs(L[j][j]) > floatEps) {
            x[j] /= L[j][j];
            for (let i = j + 1; i < n; i++) {
                x[i] -= x[j] * L[i][j];
            }
        } else {
            x[j] = 0.0;
        }
    }

    if (n > 0) {
        if (Math.abs(L[n - 1][n - 1]) > floatEps) {
            x[n - 1] /= L[n - 1][n - 1];
        } else {
            x[n - 1] = 0.0;
        }
    }

    return x;
}

""",
    "upperTriSolve": """
function upperTriSolve(U, b) {
    const floatEps = 1.0e-14;
    const n = U.length;

    
    let x = Array.from(b);

    
    for (let j = n - 1; j > 0; j--) {
        if (Math.abs(U[j][j]) > floatEps) {
            x[j] /= U[j][j];
            for (let i = 0; i < j; i++) {
                x[i] -= x[j] * U[i][j];
            }
        } else {
            x[j] = 0.0;
        }
    }

    if (n > 0) {
        if (Math.abs(U[0][0]) > floatEps) {
            x[0] /= U[0][0];
        } else {
            x[0] = 0.0;
        }
    }

    return x;
}

""",
    "modifiedCholesky": """
function modifiedCholesky(A) {
    const floatEps = 1.0e-14;
    const n = A.length;

    
    let L = deepCopy(A); 
    let p = arange(0, n);

    
    let success = true;

    let xi = 0;
    for (let i = 0; i < n; i++) {
        for (let j = 0; j < i; j++) {
            let temp = Math.abs(L[i][j]);
            xi = Math.max(xi, temp);
        }
    }

    let eta = 0;
    for (let i = 0; i < n; i++) {
        let temp = Math.abs(L[i][i]);
        eta = Math.max(eta, temp);
    }

    let beta;
    if (n > 1) {
        beta = Math.sqrt(Math.max(eta, xi / Math.sqrt(n * n - 1)));
    } else {
        beta = Math.sqrt(eta);
    }
    beta = Math.max(beta, floatEps);

    for (let k = 0; k < n; k++) {
        
        let muVal = L[k][k];
        let mu = k;
        for (let i = k + 1; i < n; i++) {
            let temp = L[i][i];
            if (muVal < temp) {
                mu = i;
                muVal = temp;
            }
        }

        
        let iTemp = p[mu];
        p[mu] = p[k];
        p[k] = iTemp;

        for (let i = 0; i < k; i++) {
            let temp = L[k][i];
            L[k][i] = L[mu][i];
            L[mu][i] = temp;
        }

        let temp = L[k][k];
        L[k][k] = L[mu][mu];
        L[mu][mu] = temp;
        for (let i = k + 1; i < mu; i++) {
            let temp = L[i][k];
            L[i][k] = L[mu][i];
            L[mu][i] = temp;
        }

        for (let i = mu + 1; i < n; i++) {
            let temp = L[i][k];
            L[i][k] = L[i][mu];
            L[i][mu] = temp;
        }

        
        let cSum = 0;
        for (let i = k + 1; i < n; i++) {
            cSum = Math.max(cSum, Math.abs(L[i][k]));
        }
        cSum /= beta;
        cSum = cSum * cSum;

        
        if (L[k][k] < 0) {
            success = false;
        }

        temp = Math.abs(L[k][k]);
        temp = Math.max(temp, floatEps * eta);
        temp = Math.max(temp, cSum);
        L[k][k] = Math.sqrt(temp);

        
        for (let i = k + 1; i < n; i++) {
            L[i][k] /= L[k][k];
        }

        
        for (let j = k + 1; j < n; j++) {
            for (let i = j; i < n; i++) {
                L[i][j] -= L[i][k] * L[j][k];
            }
        }

        
        for (let i = 0; i < n - 1; i++) {
            for (let j = i + 1; j < n; j++) {
                L[i][j] = 0.0;
            }
        }
    }

    return [L, p, success];
}

""",
    "modifiedCholeskySolve": """
function modifiedCholeskySolve(L, p, b) {
    const n = L.length;

    let U = transpose(L);
    let xp = new Array(n).fill(0);
    for (let i = 0; i < n; i++) {
        xp[i] = b[p[i]];
    }

    
    let x = lowerTriSolve(L, xp);

    
    xp = upperTriSolve(U, x);

    for (let i = 0; i < n; i++) {
        x[p[i]] = xp[i];
    }

    return x;
}

""",
    "solvePosDef": """
function solvePosDef(A, b) {
  let [L, p, success] = modifiedCholesky(A);

  if (!success) {
    return [zeros(b.length), success];
  }

  return [modifiedCholeskySolve(L, p, b), success];
}

""",
    "LUPDecompose": """
function LUPDecompose(A, eps) {
    var i, j, k, imax;
    var maxA, absA;
    var Arow;
    var p = [];
    var n = A.length;
    var LU = shallowCopyMatrix(A);

    
    for (i = 0; i <= n; i++) p.push(i);

    for (i = 0; i < n; i++) {
        maxA = 0.0;
        imax = i;

        for (k = i; k < n; k++) {
            absA = Math.abs(LU[k][i]);
            if (absA > maxA) {
                maxA = absA;
                imax = k;
            }
        }

        
        if (maxA < eps) return [null, null];

        if (imax != i) {
            
            j = p[i];
            p[i] = p[imax];
            p[imax] = j;

            
            Arow = LU[i];
            LU[i] = LU[imax];
            LU[imax] = Arow;

            
            p[n]++;
        }

        for (j = i + 1; j < n; j++) {
            LU[j][i] /= LU[i][i];

            for (k = i + 1; k < n; k++) LU[j][k] -= LU[j][i] * LU[i][k];
        }
    }

    return [LU, p];
}

""",
    "LUPSolve": """
function LUPSolve(LU, p, b) {
    var n = b.length;
    var x = [];

    for (var i = 0; i < n; i++) {
        x.push(b[p[i]]);
        for (var k = 0; k < i; k++) x[i] -= LU[i][k] * x[k];
    }

    for (i = n - 1; i >= 0; i--) {
        for (k = i + 1; k < n; k++) x[i] -= LU[i][k] * x[k];

        x[i] /= LU[i][i];
    }

    return x;
}

""",
    "solve": """
function solvePosDef(A, b) {
  let [L, p, success] = modifiedCholesky(A);

  if (!success) {
    return [zeros(b.length), success];
  }

  return [modifiedCholeskySolve(L, p, b), success];
}

""",
    "paramsFromSliders": """
function paramsFromSliders(sliders) {
  let params = [];
  for (let slider of sliders) {
    params.push(slider.value);
  }

  return params;
}

""",
    "paramsFromBoxes": """
function paramsFromBoxes(boxes) {
  let params = [];
  for (let box of boxes) {
    params.push(Number(box.value));
  }

  return params;
}

""",
    "setYRanges": """
function setYRanges(p_p, p_c, source_p) {
    p_c.y_range.start = -0.04;
    p_c.y_range.end = 1.04;        

    let pdfMax = source_p.data['y_p'];
    p_p.y_range.start = -pdfMax * 0.04;
    p_p.y_range.end = 1.04 * pdfMax;
}

""",
    "checkQuantileInput": """
function checkQuantileInput(x, p, xMin, xMax, varName, quantileSetterDiv) {
  for (let i = 0; i < x.length; i++) {
    if (p[i] <= 0 || p[i] >= 1) {
      quantileSetterDiv.text = '<p style="color:tomato;">Must have 0 < quantile < 1.</p\>';
      return false; 
    }

    if (x[i] < xMin || x[i] > xMax) {
      let qStr = '<p style="color:tomato;">Must have ' + xMin.toString() + ' ≤ yy ≤' + xMax.toString() + '.</p\>';
      quantileSetterDiv.text = qStr.replace(/yy/g, varName);
      return false;
    }
  }


  if (p.length === 2) {
    if (p[1] <= 0 || p[1] >= 1) {
        quantileSetterDiv.text = '<p style="color:tomato;">Must have 0 < quantile < 1.</p\>';
        return false;
    }

    if (p[0] >= p[1]) {
        quantileSetterDiv.text = '<p style="color:tomato;">Lower quantile must be less than upper quantile.</p\>';
        return false;
    }

    if (x[0] >= x[1]) {
        quantileSetterDiv.text = '<p style="color:tomato;">Lower yy must be less than upper yy.</p\>'.replace(/yy/g, varName);
        return false;        
    }
  }

  if (p.length === 3) {
    if (p[2] <= 0 || p[2] >= 1 || p[1] <= 0 || p[1] >= 1) {
        quantileSetterDiv.text = '<p style="color:tomato;">Must have 0 < quantile < 1.</p\>';
        return false;
    }

    if (p[0] >= p[1] || p[1] >= p[2]) {
        quantileSetterDiv.text = '<p style="color:tomato;">Quantiles must be ordered lower, middle, upper.</p\>';
        return false;
    }

    if (x[0] >= x[1] || x[1] >= x[2]) {
        quantileSetterDiv.text = '<p style="color:tomato;">yy values must be ordered, lower, middle, upper.</p\>'.replace(/yy/g, varName);
        return false;
    }
  }

    return true;
}

""",
    "jacCentralDiff": """
function jacCentralDiff(f, x, args=[], eps=4.7e-6) {
	
	let xPlus = deepCopy(x);
	let xMinus = deepCopy(x);

	
	let fOfx = f(x, ...args);
	let m = fOfx.length;

	
	let n = x.length;

	
	let J = zeros(m, n);

	
	let fOfxPlus;
	let fOfxMinus;

	for (let j = 0; j < n; j++) {
		xPlus[j] += eps;
		xMinus[j] -= eps;
		fOfxPlus = f(xPlus, ...args);
		fOfxMinus = f(xMinus, ...args);
		xPlus[j] -= eps;
		xMinus[j] += eps;

		for (let i = 0; i < m; i++) {
			J[i][j] = (fOfxPlus[i] - fOfxMinus[i]) / 2.0 / eps;
		}
	}

	return J;
}

""",
    "findRootTrustRegion": """
function findRootTrustRegion(
		f, 
		x0, 
		args=[],
		jac=jacCentralDiff,
		tol=0.000000001, 
		maxIters=10000, 
		deltaBar=1000.0, 
		eta=0.125, 
		minDelta=1e-12
  ) {
	
	let x = deepCopy(x0);

	
	let delta = 0.99 * deltaBar;

	
	let r = f(x, ...args);

	
	let J = jac(f, x, args);

	
	let JTJ = mmMult(transpose(J), J);

	
	let JTr = mvMult(transpose(J), r);

	
	let normJTr = norm(JTr);

	let iters = 0;
	while (iters < maxIters && checkTol(r, tol) && delta >= minDelta) {
		
		let p = doglegStep(JTJ, JTr, normJTr, delta);

		
		let newr = f(vectorAdd(x, p), ...args);
		let rho = computeRho(r, newr, J, p);

		
		if  (rho < 0.25) {
			delta = norm(p) / 4.0;
		} else if (rho > 0.75 && Math.abs(norm(p) - delta) < 1e-12) {
				delta = Math.min(2 * delta, deltaBar);
		}

		
		if (rho > eta) {
			x = vectorAdd(x, p);

			r = newr;
			J = jac(f, x, args);
			JTJ = mmMult(transpose(J), J);
			JTr = mvMult(transpose(J), r);
			normJTr = norm(JTr);
		}

		iters += 1;
	}

	let success = !checkTol(r, tol);

	return [x, success];

}

""",
    "computeRho": """
function computeRho(r, newr, J, p) {
	let r2 = norm(r) ** 2;
	let num = r2 - norm(newr)**2;
	let denom = r2 - norm(vectorAdd(r, mvMult(J, p))) ** 2;

	return num / denom;
}

""",
    "checkTol": """
function checkTol(r, tol) {
	
	const n = r.length;
	for (let i = 0; i < n; i++) {
		if (tol < Math.abs(r[i])) return true;
	}

	return false;
}

""",
    "doglegStep": """
function doglegStep(JTJ, JTr, normJTr, delta) {
	
	let [pJ, posDef] = solvePosDef(JTJ, JTr);
	pJ = svMult(-1.0, pJ);

	
	if (posDef && norm(pJ) <= delta) {
		return pJ;
	}

	
	let tau = Math.min(1, normJTr**3 / delta / quadForm(JTJ, JTr));
	let pC = svMult(-tau * delta / normJTr, JTr);

	let pCnorm = norm(pC);
	if (!posDef || Math.abs(pCnorm - delta) <= 1e-12) {
		return pC;
	}

	
	let pJ2 = norm(pJ) ** 2;
	let pC2 = pCnorm**2;
	let pJpC = dot(pJ, pC);
	let a = pJ2 + pC2 - 2.0 * pJpC;
	let b = 2.0 * (pJpC - pC2);
	let c = pC2 - delta**2;
	let q = -0.5 * (b + Math.sign(b) * Math.sqrt(b**2 - 4.0 * a * c));

	
	let beta;
	if (Math.abs(b) < 1e-12) beta = Math.sqrt(-c / a);
	else if (b < 0.0) beta = q / a;
	else beta = c / q;

	
	if (0.0 <= beta && beta <= 1) {
		return vectorAdd(pC, svMult(beta, vectorAdd(pJ, svMult(-1.0, pC))));
	} else { 
		return pC;
	}

}

""",
    "newtonSolve": """
function newtonSolve(x0, f, df, args=[], tol=1e-8, maxIter=200, epsilon=1e-14) {
	let x = Infinity;
	let solved = false;

  for (let i = 0; i < maxIter; i++) {
      let y = f(x0, ...args);
      let yprime = df(x0, ...args);

      if (Math.abs(yprime) < epsilon) {
      	break;
			}

      x = x0 - y / yprime;

      if (Math.abs(x - x0) <= tol) {
      	solved = true;
      	break;
      }

      x0 = x;
  }

  if (solved) return x;
  else return null;
}

""",
    "secantSolve": """
function secantSolve(x0, f, args=[], tol=1e-8, maxIter=200, epsilon=1e-14, h=1e-4) {
	let x = Infinity;
	let solved = false;

	let x1 = x0 * (1 + h);
	x1 += x1 >= 0 ? h : -h;

	let q0 = f(x0, ...args);
	let q1 = f(x1, ...args);
	
	if (Math.abs(q1) < Math.abs(q0)) {
		[x0, x1, q0, q1] = [x1, x0, q1, q0];
	}

	for (let i = 0; i < maxIter; i++) {
		if (q0 == q1) {
			solved = x0 == x1;
			x = (x0 + x1) / 2.0;
			break;
		}
		else {
			if (Math.abs(q1) > Math.abs(q0)) {
				x = (x0 - q0 / q1 * x1) / (1.0 - q0 / q1);
			}
			else {
				x = (x1 - q1 / q0 * x0) / (1.0 - q1 / q0);
			}
			if (Math.abs(x - x0) <= tol) {
				solved = true;
				break;
			}
			[x0, q0] = [x1, q1];
			x1 = x;
			q1 = f(x1, ...args);
		}
	}

  if (solved) return x;
  else return null;
}

""",
    "brentSolve": """
function brentSolve(f, lower, upper, args=[], tol=1e-8, maxIter=1000) {
	let a = lower;
	let b = upper;
  let fa = f(a, ...args);
  let fb = f(b, ...args);

  
  if (Math.abs(fa) < tol) return a;
  if (Math.abs(fb) < tol) return b;

  
  if (fa * fb >= 0) {
  	return null;
	}

  
  let c = a;
  let fc = fa;

	let iter = 0;
  while (iter++ < maxIter) {
  	let prevStep = b - a;

    
    if (Math.abs(fc) < Math.abs(fb)) {      
    	[a, b, c] = [b, c, b];
    	[fa, fb, fc] = [fb, fc, fb];
    }

    
    let newStep = (c - b) / 2.0;

    
    let tolAdj = 1e-15 * Math.abs(b) + tol / 2;

    
  	if (Math.abs(newStep) <= tolAdj || fb === 0 ) {
    		return b;
  	}

    
    if (Math.abs(prevStep) > tolAdj && Math.abs(fa) > Math.abs(fb)) {
    	let p;
    	let q;
    	let t1;
    	let t2;
    	let cb = c - b;
    	if (a === c) { 
    		t1 = fb / fa;
    		p = cb * t1;
    		q = 1.0 - t1;
    	}
    	else { 
    		q = fa / fc;
    		t1 = fb / fc;
    		t2 = fb / fa;
    		p = t2 * (cb * q * (q - t1) - (b - a) * (t1 - 1.0));
    		q = (q - 1.0) * (t1 - 1.0) * (t2 - 1.0);
    	}

    	
    	if (p > 0) q = -q;
    	else p = -p;

    	
    	if (p < (0.75 * cb * q - Math.abs(tolAdj * q) / 2.0) 
    		&& p < Math.abs(prevStep * q / 2.0)) { 
	        newStep = p / q;
      	}
    }

    if (Math.abs(newStep) < tolAdj) {
      newStep = (newStep > 0) ? tolAdj : -tolAdj;
    }

    
    a = b;
    fa = fb;

    
    b += newStep;
    fb = f(b, ...args);

	
    if ((fb > 0 && fc > 0) || (fb < 0 && fc < 0)) {
      c = a; 
      fc = fa;
    }
  }

  
  return null;
}

""",
    "slider_start_callback": """

slider.start = Math.max(minValue, Number(cb_obj.value));
slider.step = (slider.end - slider.start) / 1000;""",
    "slider_end_callback": """

slider.end = Math.min(maxValue, Number(cb_obj.value));
slider.step = (slider.end - slider.start) / 1000;""",
    "int_slider_start_callback": """


slider.start = Math.max(Math.floor(minValue), Math.floor(Number(cb_obj.value)));""",
    "int_slider_end_callback": """


slider.end = Math.min(Math.floor(maxValue), Math.floor(Number(cb_obj.value)));""",
    "quantile_setter_switch_callback": """

if (cb_obj.active) {
  for (let i = 0; i < sliders.length; i++) {
      sliders[i].disabled = true;
  }
  for (let xBox of xBoxes) {
    xBox.disabled = false;
  }
  for (let pBox of pBoxes) {
    pBox.disabled = false;
  }
} else {
  for (let i = 0; i < sliders.length; i++) {
      sliders[i].disabled = false;
  }
  for (let xBox of xBoxes) {
    xBox.disabled = true;
  }
  for (let pBox of pBoxes) {
    pBox.disabled = true;
  }
  quantileSetterDiv.text = '';
}""",
    "quantile_setter_callback": """

if (quantileSetterSwitch.active) {
  
  let x = paramsFromBoxes(xBoxes);
  let p = paramsFromBoxes(pBoxes);

  
  let params = paramsFromSliders(sliders);

  
  let inputOk = checkQuantileInput(x, p, dist.hardMin, dist.hardMax, dist.varName, quantileSetterDiv);

  if (inputOk) {
    
    let extraParams = [];
    for (let i = 0; i < dist.paramNames.length; i++) {
      if (dist.fixedParamsInds.includes(i)) {
        extraParams.push(params[i]);
      }
    }

    
    let [optimParams, optimSuccess] = dist.quantileSet(x, p, extraParams);

    let text;
    if (optimSuccess) {
      
      text = '<p>';
      for (let i = 0; i < optimParams.length - 1; i++) {
        text += sliders[dist.activeParamsInds[i]].title + ' = ' + optimParams[i].toPrecision(4) + ', ';
      }
      let i = optimParams.length - 1;
      text += sliders[dist.activeParamsInds[i]].title + ' = ' + optimParams[i].toPrecision(4) + '</p>';
    } else{
      text = '<p style="color:tomato;">Failed to find parameters to match quantiles.</p>';
    }

    quantileSetterDiv.text = text;

    if (optimSuccess) {
      
      for (let i = 0; i < optimParams.length; i++ ){
        if (sliders[dist.activeParamsInds[i]].start > optimParams[i] || sliders[dist.activeParamsInds[i]].end < optimParams[i]) {
          startBoxes[dist.activeParamsInds[i]].value = (4 * optimParams[i] / 1001).toPrecision(4);
          endBoxes[dist.activeParamsInds[i]].value = (4 * optimParams[i]).toPrecision(4);        
        }
        sliders[dist.activeParamsInds[i]].value = optimParams[i];
      }

      params = paramsFromSliders(sliders); 

      
      let [x1, x2] = dist.defaultXRange(params);

      p_p.x_range.start = x1;
      p_p.x_range.end = x2;

      
      setYRanges(p_p, p_c, source_p);  
    }
  }
}""",
    "reset_button_callback": """

let params = paramsFromSliders(sliders); 


let [x1, x2] = dist.defaultXRange(params);

if (p_p.x_range.start != x1 && p_p.x_range.end != x2) {
  p_p.x_range.start = x1;
  p_p.x_range.end = x2;
}


setYRanges(p_p, p_c, source_p);  
""",
    "continuous_callback": """

let x_p = source_p.data['x'];
let y_p = source_p.data['y_p'];
let x_c = source_c.data['x'];
let y_c = source_c.data['y_c'];
let xRangeMin = xRange.start;
let xRangeMax = xRange.end;


x_p = linspace(xRangeMin, xRangeMax, n);
x_c = x_p;


source_p.data['x'] = x_p;
source_c.data['x'] = x_c;


let params = paramsFromSliders(sliders);


let pdf = dist.pdf(x_p, params);


pdf = pdf.map(val => (val === Infinity || val === -Infinity) ? NaN : val);


source_p.data['y_p'] = pdf;
source_c.data['y_c'] = dist.cdf(x_c, params);

if (!quantileSetterSwitch.active) {
	for (let i = 0; i < xBoxes.length; i++) {
		xBoxes[i].value = dist.ppfSingleValue(Number(pBoxes[i].value), params).toPrecision(4);
	}
}

source_p.change.emit();
source_c.change.emit();""",
    "discrete_callback": """

let xRangeMin = Math.floor(xRange.start);
let xRangeMax = Math.ceil(xRange.end);


let x_p = arange(xRangeMin, xRangeMax + 1);


let x_c = [xRangeMin - 1, ...x_p.flatMap(x => [x, x]), xRangeMax + 1];


source_p.data['x'] = x_p;
source_c.data['x'] = x_c;


let params = paramsFromSliders(sliders);


source_p.data['y_p'] = dist.pmf(x_p, params);
source_c.data['y_c'] = dist.cdfForPlotting(x_c[0], x_c[x_c.length - 1], params, dist.xMin(params));

source_p.change.emit();
source_c.change.emit();""",
}

_dependencies = {
    "UnivariateDistribution": [],
    "DiscreteUnivariateDistribution": ['UnivariateDistribution', 'isclose'],
    "ContinuousUnivariateDistribution": ['UnivariateDistribution'],
    "TemplateDiscreteUnivariateDistribution": ['UnivariateDistribution', 'DiscreteUnivariateDistribution', 'isclose'],
    "TemplateContinuousUnivariateDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution'],
    "BernoulliDistribution": ['UnivariateDistribution', 'DiscreteUnivariateDistribution', 'isclose'],
    "BetaBinomialDistribution": ['UnivariateDistribution', 'DiscreteUnivariateDistribution', 'lnchoice', 'lnbeta', 'lnfactorial', 'lngamma', 'isclose'],
    "BinomialDistribution": ['UnivariateDistribution', 'DiscreteUnivariateDistribution', 'lnchoice', 'lnfactorial', 'isclose'],
    "CategoricalDistribution": ['UnivariateDistribution', 'DiscreteUnivariateDistribution', 'isclose'],
    "DiscreteUniformDistribution": ['UnivariateDistribution', 'DiscreteUnivariateDistribution', 'isclose'],
    "GeometricDistribution": ['UnivariateDistribution', 'DiscreteUnivariateDistribution', 'isclose'],
    "HypergeometricDistribution": ['UnivariateDistribution', 'DiscreteUnivariateDistribution', 'lnchoice', 'lnfactorial', 'isclose'],
    "NegativeBinomialDistribution": ['UnivariateDistribution', 'DiscreteUnivariateDistribution', 'lngamma', 'lnfactorial', 'isclose'],
    "NegativeBinomialMuPhiDistribution": [],
    "NegativeBinomialRBDistribution": [],
    "PoissonDistribution": ['UnivariateDistribution', 'DiscreteUnivariateDistribution', 'lnfactorial', 'isclose'],
    "BetaDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution', 'isone', 'iszero', 'lnbeta', 'regularizedIncompleteBeta', 'findRootTrustRegion', 'brentSolve', 'isclose', 'lngamma', 'log1p', 'betacf', 'transpose', 'mvMult', 'mmMult', 'vectorAdd', 'norm', 'deepCopy', 'computeRho', 'checkTol', 'doglegStep', 'jacCentralDiff', 'dot', 'zeros', 'svMult', 'quadForm', 'solvePosDef', 'modifiedCholesky', 'modifiedCholeskySolve', 'arange', 'lowerTriSolve', 'upperTriSolve'],
    "CauchyDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution'],
    "ExponentialDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution'],
    "GammaDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution', 'lngamma', 'gammaincL', 'norm', 'findRootTrustRegion', 'secantSolve', 'brentSolve', 'gammaincU', 'dot', 'transpose', 'mvMult', 'mmMult', 'vectorAdd', 'deepCopy', 'computeRho', 'checkTol', 'doglegStep', 'jacCentralDiff', 'zeros', 'svMult', 'quadForm', 'solvePosDef', 'modifiedCholesky', 'modifiedCholeskySolve', 'arange', 'lowerTriSolve', 'upperTriSolve'],
    "HalfCauchyDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution'],
    "HalfNormalDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution', 'erf', 'erfinv'],
    "HalfStudentTDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution', 'CauchyDistribution', 'HalfCauchyDistribution', 'HalfNormalDistribution', 'NormalDistribution', 'StudentTDistribution', 'log1p', 'regularizedIncompleteBeta', 'lngamma', 'norm', 'findRootTrustRegion', 'erf', 'erfinv', 'betacf', 'dot', 'transpose', 'mvMult', 'mmMult', 'vectorAdd', 'deepCopy', 'computeRho', 'checkTol', 'doglegStep', 'jacCentralDiff', 'zeros', 'svMult', 'quadForm', 'solvePosDef', 'modifiedCholesky', 'modifiedCholeskySolve', 'arange', 'lowerTriSolve', 'upperTriSolve'],
    "InverseGammaDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution', 'GammaDistribution', 'lngamma', 'gammaincU', 'gammaincL', 'norm', 'findRootTrustRegion', 'secantSolve', 'brentSolve', 'dot', 'transpose', 'mvMult', 'mmMult', 'vectorAdd', 'deepCopy', 'computeRho', 'checkTol', 'doglegStep', 'jacCentralDiff', 'zeros', 'svMult', 'quadForm', 'solvePosDef', 'modifiedCholesky', 'modifiedCholeskySolve', 'arange', 'lowerTriSolve', 'upperTriSolve'],
    "LogNormalDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution', 'erf', 'erfinv'],
    "NormalDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution', 'erf', 'erfinv'],
    "ParetoDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution'],
    "StudentTDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution', 'CauchyDistribution', 'NormalDistribution', 'log1p', 'erfinv', 'regularizedIncompleteBeta', 'lngamma', 'norm', 'findRootTrustRegion', 'erf', 'betacf', 'dot', 'transpose', 'mvMult', 'mmMult', 'vectorAdd', 'deepCopy', 'computeRho', 'checkTol', 'doglegStep', 'jacCentralDiff', 'zeros', 'svMult', 'quadForm', 'solvePosDef', 'modifiedCholesky', 'modifiedCholeskySolve', 'arange', 'lowerTriSolve', 'upperTriSolve'],
    "UniformDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution'],
    "WeibullDistribution": ['UnivariateDistribution', 'ContinuousUnivariateDistribution'],
    "isclose": [],
    "isone": ['isclose'],
    "iszero": [],
    "logspace": [],
    "linspace": [],
    "arange": [],
    "meshgrid": [],
    "logit": [],
    "log1p": [],
    "erf": [],
    "erfinv": [],
    "lnchoice": ['lnfactorial'],
    "lnbeta": ['lngamma'],
    "betacf": [],
    "regularizedIncompleteBeta": ['log1p', 'betacf', 'lngamma'],
    "incompleteBeta": ['lnbeta', 'regularizedIncompleteBeta', 'lngamma', 'log1p', 'betacf'],
    "lngamma": [],
    "gammaincU": ['lngamma', 'gammaincL', 'gammaincU'],
    "gammaincL": ['lngamma', 'gammaincU', 'gammaincL'],
    "lnfactorial": [],
    "transpose": [],
    "mvMult": ['dot'],
    "svMult": [],
    "smMult": ['svMult'],
    "svAdd": [],
    "mmMult": ['zeros', 'deepCopy'],
    "vectorAdd": [],
    "elementwiseVectorDivide": [],
    "elementwiseVectorMult": [],
    "svMultAdd": [],
    "absVector": [],
    "dot": [],
    "norm": ['dot'],
    "quadForm": ['mvMult', 'dot'],
    "shallowCopyMatrix": [],
    "deepCopy": [],
    "zeros": ['deepCopy'],
    "lowerTriSolve": [],
    "upperTriSolve": [],
    "modifiedCholesky": ['arange', 'deepCopy'],
    "modifiedCholeskySolve": ['transpose', 'lowerTriSolve', 'upperTriSolve'],
    "solvePosDef": ['zeros', 'modifiedCholesky', 'modifiedCholeskySolve', 'deepCopy', 'arange', 'transpose', 'lowerTriSolve', 'upperTriSolve'],
    "LUPDecompose": ['shallowCopyMatrix'],
    "LUPSolve": [],
    "solve": ['zeros', 'modifiedCholesky', 'modifiedCholeskySolve', 'solvePosDef', 'deepCopy', 'arange', 'transpose', 'lowerTriSolve', 'upperTriSolve'],
    "paramsFromSliders": [],
    "paramsFromBoxes": [],
    "setYRanges": [],
    "checkQuantileInput": [],
    "jacCentralDiff": ['deepCopy', 'zeros'],
    "findRootTrustRegion": ['transpose', 'mvMult', 'mmMult', 'vectorAdd', 'norm', 'deepCopy', 'computeRho', 'checkTol', 'doglegStep', 'jacCentralDiff', 'dot', 'zeros', 'svMult', 'quadForm', 'solvePosDef', 'modifiedCholesky', 'modifiedCholeskySolve', 'arange', 'lowerTriSolve', 'upperTriSolve'],
    "computeRho": ['mvMult', 'vectorAdd', 'norm', 'dot'],
    "checkTol": [],
    "doglegStep": ['svMult', 'vectorAdd', 'dot', 'norm', 'quadForm', 'solvePosDef', 'mvMult', 'zeros', 'modifiedCholesky', 'modifiedCholeskySolve', 'deepCopy', 'arange', 'transpose', 'lowerTriSolve', 'upperTriSolve'],
    "newtonSolve": [],
    "secantSolve": [],
    "brentSolve": [],
    "slider_start_callback": [],
    "slider_end_callback": [],
    "int_slider_start_callback": [],
    "int_slider_end_callback": [],
    "quantile_setter_switch_callback": [],
    "quantile_setter_callback": ['paramsFromSliders', 'paramsFromBoxes', 'setYRanges', 'checkQuantileInput'],
    "reset_button_callback": ['paramsFromSliders', 'setYRanges'],
    "continuous_callback": ['linspace', 'paramsFromSliders'],
    "discrete_callback": ['arange', 'paramsFromSliders'],
}